site: Resul Kavakli

title: Resul Kavakli
description: thoughts and notes about software engineering.
twitter:
  username: rlskvk
  card: summary
  creator: rlskvk
author:
  twitter: rslkvk
  name: rslkvk
  avatar:
  email: resul[dot]kavakli[at]gmail[dot]com
  url: https://resulkavakli.de
permalink: pretty

baseurl: ""

highlighter: Rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
